base_dir: /data/data/com.termux/files/home/BIG-Projects/SHADOW_GRIMORIO
shadow_alias: ShadowRoot07
shadow_env: development
shadow_theme: CYBERZEN
sounds_path: assets/sounds
lexicon_path: /data/data/com.termux/files/home/BIG-Projects/SHADOW_GRIMORIO/logs/lexicon_index.json
github_username: ShadowRoot07
groq_model: llama3-70b-8192
groq_timeout: 30
groq_cooldown: 2
groq_retry_limit: 3
