"""Add Project and History tables

Revision ID: 5ac944c7ec6f
Revises: 3622ba4d63e9
Create Date: 2026-05-02 22:10:59.612059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac944c7ec6f'
down_revision: Union[str, Sequence[str], None] = '3622ba4d63e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('path_local', sa.String(), nullable=False),
    sa.Column('rama_actual', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hitos_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('mensaje_commit', sa.Text(), nullable=True),
    sa.Column('prompt_usuario', sa.Text(), nullable=True),
    sa.Column('respuesta_ia', sa.Text(), nullable=True),
    sa.Column('contexto_tecnico', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hitos_historial')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
